/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "../common";

export interface BotSettingsInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "activateBot"
      | "allowedCategories"
      | "botConfigs"
      | "canPlaceBet"
      | "clearEmergencyStop"
      | "configureBotSettings"
      | "deactivateBot"
      | "emergencyStop"
      | "getAllowedCategories"
      | "getBotConfig"
      | "getBotStats"
      | "hasPlacedBet"
      | "isBotActive"
      | "owner"
      | "recordBet"
      | "recordLoss"
      | "renounceOwnership"
      | "transferOwnership"
      | "triggerEmergencyStop"
  ): FunctionFragment;

  getEvent(
    nameOrSignatureOrTopic:
      | "BetRecorded"
      | "BotActivated"
      | "BotConfigured"
      | "BotDeactivated"
      | "BudgetReset"
      | "EmergencyStopTriggered"
      | "OwnershipTransferred"
  ): EventFragment;

  encodeFunctionData(
    functionFragment: "activateBot",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "allowedCategories",
    values: [AddressLike, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "botConfigs",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "canPlaceBet",
    values: [AddressLike, string, string, BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "clearEmergencyStop",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "configureBotSettings",
    values: [
      BigNumberish,
      BigNumberish,
      BigNumberish,
      BigNumberish,
      BigNumberish,
      BigNumberish,
      BigNumberish,
      string[]
    ]
  ): string;
  encodeFunctionData(
    functionFragment: "deactivateBot",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "emergencyStop",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "getAllowedCategories",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "getBotConfig",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "getBotStats",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "hasPlacedBet",
    values: [AddressLike, string]
  ): string;
  encodeFunctionData(
    functionFragment: "isBotActive",
    values: [AddressLike]
  ): string;
  encodeFunctionData(functionFragment: "owner", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "recordBet",
    values: [string, string, BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "recordLoss",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "renounceOwnership",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "transferOwnership",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "triggerEmergencyStop",
    values: [string]
  ): string;

  decodeFunctionResult(
    functionFragment: "activateBot",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "allowedCategories",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "botConfigs", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "canPlaceBet",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "clearEmergencyStop",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "configureBotSettings",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "deactivateBot",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "emergencyStop",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getAllowedCategories",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getBotConfig",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getBotStats",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "hasPlacedBet",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "isBotActive",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "owner", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "recordBet", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "recordLoss", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "renounceOwnership",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "transferOwnership",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "triggerEmergencyStop",
    data: BytesLike
  ): Result;
}

export namespace BetRecordedEvent {
  export type InputTuple = [
    user: AddressLike,
    marketId: string,
    amount: BigNumberish,
    timestamp: BigNumberish
  ];
  export type OutputTuple = [
    user: string,
    marketId: string,
    amount: bigint,
    timestamp: bigint
  ];
  export interface OutputObject {
    user: string;
    marketId: string;
    amount: bigint;
    timestamp: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace BotActivatedEvent {
  export type InputTuple = [user: AddressLike, timestamp: BigNumberish];
  export type OutputTuple = [user: string, timestamp: bigint];
  export interface OutputObject {
    user: string;
    timestamp: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace BotConfiguredEvent {
  export type InputTuple = [
    user: AddressLike,
    maxBetPerMarket: BigNumberish,
    dailyBudget: BigNumberish,
    weeklyBudget: BigNumberish,
    minConfidence: BigNumberish
  ];
  export type OutputTuple = [
    user: string,
    maxBetPerMarket: bigint,
    dailyBudget: bigint,
    weeklyBudget: bigint,
    minConfidence: bigint
  ];
  export interface OutputObject {
    user: string;
    maxBetPerMarket: bigint;
    dailyBudget: bigint;
    weeklyBudget: bigint;
    minConfidence: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace BotDeactivatedEvent {
  export type InputTuple = [user: AddressLike, timestamp: BigNumberish];
  export type OutputTuple = [user: string, timestamp: bigint];
  export interface OutputObject {
    user: string;
    timestamp: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace BudgetResetEvent {
  export type InputTuple = [
    user: AddressLike,
    resetType: string,
    timestamp: BigNumberish
  ];
  export type OutputTuple = [
    user: string,
    resetType: string,
    timestamp: bigint
  ];
  export interface OutputObject {
    user: string;
    resetType: string;
    timestamp: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace EmergencyStopTriggeredEvent {
  export type InputTuple = [
    user: AddressLike,
    reason: string,
    timestamp: BigNumberish
  ];
  export type OutputTuple = [user: string, reason: string, timestamp: bigint];
  export interface OutputObject {
    user: string;
    reason: string;
    timestamp: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace OwnershipTransferredEvent {
  export type InputTuple = [previousOwner: AddressLike, newOwner: AddressLike];
  export type OutputTuple = [previousOwner: string, newOwner: string];
  export interface OutputObject {
    previousOwner: string;
    newOwner: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface BotSettings extends BaseContract {
  connect(runner?: ContractRunner | null): BotSettings;
  waitForDeployment(): Promise<this>;

  interface: BotSettingsInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  activateBot: TypedContractMethod<[], [void], "nonpayable">;

  allowedCategories: TypedContractMethod<
    [arg0: AddressLike, arg1: BigNumberish],
    [string],
    "view"
  >;

  botConfigs: TypedContractMethod<
    [arg0: AddressLike],
    [
      [
        boolean,
        bigint,
        bigint,
        bigint,
        bigint,
        bigint,
        bigint,
        bigint,
        bigint,
        bigint,
        bigint,
        bigint,
        bigint,
        bigint,
        bigint
      ] & {
        isActive: boolean;
        maxBetPerMarket: bigint;
        dailyBudget: bigint;
        weeklyBudget: bigint;
        minConfidence: bigint;
        maxBetsPerDay: bigint;
        cooldownMinutes: bigint;
        emergencyStopLoss: bigint;
        lastBetTimestamp: bigint;
        dailySpent: bigint;
        weeklySpent: bigint;
        totalLosses: bigint;
        betsToday: bigint;
        lastResetDay: bigint;
        lastResetWeek: bigint;
      }
    ],
    "view"
  >;

  canPlaceBet: TypedContractMethod<
    [
      user: AddressLike,
      marketId: string,
      category: string,
      betAmount: BigNumberish,
      aiConfidence: BigNumberish
    ],
    [[boolean, string]],
    "view"
  >;

  clearEmergencyStop: TypedContractMethod<[], [void], "nonpayable">;

  configureBotSettings: TypedContractMethod<
    [
      _maxBetPerMarket: BigNumberish,
      _dailyBudget: BigNumberish,
      _weeklyBudget: BigNumberish,
      _minConfidence: BigNumberish,
      _maxBetsPerDay: BigNumberish,
      _cooldownMinutes: BigNumberish,
      _emergencyStopLoss: BigNumberish,
      _allowedCategories: string[]
    ],
    [void],
    "nonpayable"
  >;

  deactivateBot: TypedContractMethod<[], [void], "nonpayable">;

  emergencyStop: TypedContractMethod<[arg0: AddressLike], [boolean], "view">;

  getAllowedCategories: TypedContractMethod<
    [user: AddressLike],
    [string[]],
    "view"
  >;

  getBotConfig: TypedContractMethod<
    [user: AddressLike],
    [
      [boolean, bigint, bigint, bigint, bigint, bigint, bigint, bigint] & {
        isActive: boolean;
        maxBetPerMarket: bigint;
        dailyBudget: bigint;
        weeklyBudget: bigint;
        minConfidence: bigint;
        maxBetsPerDay: bigint;
        cooldownMinutes: bigint;
        emergencyStopLoss: bigint;
      }
    ],
    "view"
  >;

  getBotStats: TypedContractMethod<
    [user: AddressLike],
    [
      [bigint, bigint, bigint, bigint, bigint, boolean] & {
        dailySpent: bigint;
        weeklySpent: bigint;
        totalLosses: bigint;
        betsToday: bigint;
        lastBetTimestamp: bigint;
        emergencyStopActive: boolean;
      }
    ],
    "view"
  >;

  hasPlacedBet: TypedContractMethod<
    [arg0: AddressLike, arg1: string],
    [boolean],
    "view"
  >;

  isBotActive: TypedContractMethod<[user: AddressLike], [boolean], "view">;

  owner: TypedContractMethod<[], [string], "view">;

  recordBet: TypedContractMethod<
    [
      marketId: string,
      category: string,
      amount: BigNumberish,
      aiConfidence: BigNumberish
    ],
    [void],
    "nonpayable"
  >;

  recordLoss: TypedContractMethod<
    [lossAmount: BigNumberish],
    [void],
    "nonpayable"
  >;

  renounceOwnership: TypedContractMethod<[], [void], "nonpayable">;

  transferOwnership: TypedContractMethod<
    [newOwner: AddressLike],
    [void],
    "nonpayable"
  >;

  triggerEmergencyStop: TypedContractMethod<
    [reason: string],
    [void],
    "nonpayable"
  >;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "activateBot"
  ): TypedContractMethod<[], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "allowedCategories"
  ): TypedContractMethod<
    [arg0: AddressLike, arg1: BigNumberish],
    [string],
    "view"
  >;
  getFunction(
    nameOrSignature: "botConfigs"
  ): TypedContractMethod<
    [arg0: AddressLike],
    [
      [
        boolean,
        bigint,
        bigint,
        bigint,
        bigint,
        bigint,
        bigint,
        bigint,
        bigint,
        bigint,
        bigint,
        bigint,
        bigint,
        bigint,
        bigint
      ] & {
        isActive: boolean;
        maxBetPerMarket: bigint;
        dailyBudget: bigint;
        weeklyBudget: bigint;
        minConfidence: bigint;
        maxBetsPerDay: bigint;
        cooldownMinutes: bigint;
        emergencyStopLoss: bigint;
        lastBetTimestamp: bigint;
        dailySpent: bigint;
        weeklySpent: bigint;
        totalLosses: bigint;
        betsToday: bigint;
        lastResetDay: bigint;
        lastResetWeek: bigint;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "canPlaceBet"
  ): TypedContractMethod<
    [
      user: AddressLike,
      marketId: string,
      category: string,
      betAmount: BigNumberish,
      aiConfidence: BigNumberish
    ],
    [[boolean, string]],
    "view"
  >;
  getFunction(
    nameOrSignature: "clearEmergencyStop"
  ): TypedContractMethod<[], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "configureBotSettings"
  ): TypedContractMethod<
    [
      _maxBetPerMarket: BigNumberish,
      _dailyBudget: BigNumberish,
      _weeklyBudget: BigNumberish,
      _minConfidence: BigNumberish,
      _maxBetsPerDay: BigNumberish,
      _cooldownMinutes: BigNumberish,
      _emergencyStopLoss: BigNumberish,
      _allowedCategories: string[]
    ],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "deactivateBot"
  ): TypedContractMethod<[], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "emergencyStop"
  ): TypedContractMethod<[arg0: AddressLike], [boolean], "view">;
  getFunction(
    nameOrSignature: "getAllowedCategories"
  ): TypedContractMethod<[user: AddressLike], [string[]], "view">;
  getFunction(
    nameOrSignature: "getBotConfig"
  ): TypedContractMethod<
    [user: AddressLike],
    [
      [boolean, bigint, bigint, bigint, bigint, bigint, bigint, bigint] & {
        isActive: boolean;
        maxBetPerMarket: bigint;
        dailyBudget: bigint;
        weeklyBudget: bigint;
        minConfidence: bigint;
        maxBetsPerDay: bigint;
        cooldownMinutes: bigint;
        emergencyStopLoss: bigint;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "getBotStats"
  ): TypedContractMethod<
    [user: AddressLike],
    [
      [bigint, bigint, bigint, bigint, bigint, boolean] & {
        dailySpent: bigint;
        weeklySpent: bigint;
        totalLosses: bigint;
        betsToday: bigint;
        lastBetTimestamp: bigint;
        emergencyStopActive: boolean;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "hasPlacedBet"
  ): TypedContractMethod<[arg0: AddressLike, arg1: string], [boolean], "view">;
  getFunction(
    nameOrSignature: "isBotActive"
  ): TypedContractMethod<[user: AddressLike], [boolean], "view">;
  getFunction(
    nameOrSignature: "owner"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "recordBet"
  ): TypedContractMethod<
    [
      marketId: string,
      category: string,
      amount: BigNumberish,
      aiConfidence: BigNumberish
    ],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "recordLoss"
  ): TypedContractMethod<[lossAmount: BigNumberish], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "renounceOwnership"
  ): TypedContractMethod<[], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "transferOwnership"
  ): TypedContractMethod<[newOwner: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "triggerEmergencyStop"
  ): TypedContractMethod<[reason: string], [void], "nonpayable">;

  getEvent(
    key: "BetRecorded"
  ): TypedContractEvent<
    BetRecordedEvent.InputTuple,
    BetRecordedEvent.OutputTuple,
    BetRecordedEvent.OutputObject
  >;
  getEvent(
    key: "BotActivated"
  ): TypedContractEvent<
    BotActivatedEvent.InputTuple,
    BotActivatedEvent.OutputTuple,
    BotActivatedEvent.OutputObject
  >;
  getEvent(
    key: "BotConfigured"
  ): TypedContractEvent<
    BotConfiguredEvent.InputTuple,
    BotConfiguredEvent.OutputTuple,
    BotConfiguredEvent.OutputObject
  >;
  getEvent(
    key: "BotDeactivated"
  ): TypedContractEvent<
    BotDeactivatedEvent.InputTuple,
    BotDeactivatedEvent.OutputTuple,
    BotDeactivatedEvent.OutputObject
  >;
  getEvent(
    key: "BudgetReset"
  ): TypedContractEvent<
    BudgetResetEvent.InputTuple,
    BudgetResetEvent.OutputTuple,
    BudgetResetEvent.OutputObject
  >;
  getEvent(
    key: "EmergencyStopTriggered"
  ): TypedContractEvent<
    EmergencyStopTriggeredEvent.InputTuple,
    EmergencyStopTriggeredEvent.OutputTuple,
    EmergencyStopTriggeredEvent.OutputObject
  >;
  getEvent(
    key: "OwnershipTransferred"
  ): TypedContractEvent<
    OwnershipTransferredEvent.InputTuple,
    OwnershipTransferredEvent.OutputTuple,
    OwnershipTransferredEvent.OutputObject
  >;

  filters: {
    "BetRecorded(address,string,uint256,uint256)": TypedContractEvent<
      BetRecordedEvent.InputTuple,
      BetRecordedEvent.OutputTuple,
      BetRecordedEvent.OutputObject
    >;
    BetRecorded: TypedContractEvent<
      BetRecordedEvent.InputTuple,
      BetRecordedEvent.OutputTuple,
      BetRecordedEvent.OutputObject
    >;

    "BotActivated(address,uint256)": TypedContractEvent<
      BotActivatedEvent.InputTuple,
      BotActivatedEvent.OutputTuple,
      BotActivatedEvent.OutputObject
    >;
    BotActivated: TypedContractEvent<
      BotActivatedEvent.InputTuple,
      BotActivatedEvent.OutputTuple,
      BotActivatedEvent.OutputObject
    >;

    "BotConfigured(address,uint256,uint256,uint256,uint256)": TypedContractEvent<
      BotConfiguredEvent.InputTuple,
      BotConfiguredEvent.OutputTuple,
      BotConfiguredEvent.OutputObject
    >;
    BotConfigured: TypedContractEvent<
      BotConfiguredEvent.InputTuple,
      BotConfiguredEvent.OutputTuple,
      BotConfiguredEvent.OutputObject
    >;

    "BotDeactivated(address,uint256)": TypedContractEvent<
      BotDeactivatedEvent.InputTuple,
      BotDeactivatedEvent.OutputTuple,
      BotDeactivatedEvent.OutputObject
    >;
    BotDeactivated: TypedContractEvent<
      BotDeactivatedEvent.InputTuple,
      BotDeactivatedEvent.OutputTuple,
      BotDeactivatedEvent.OutputObject
    >;

    "BudgetReset(address,string,uint256)": TypedContractEvent<
      BudgetResetEvent.InputTuple,
      BudgetResetEvent.OutputTuple,
      BudgetResetEvent.OutputObject
    >;
    BudgetReset: TypedContractEvent<
      BudgetResetEvent.InputTuple,
      BudgetResetEvent.OutputTuple,
      BudgetResetEvent.OutputObject
    >;

    "EmergencyStopTriggered(address,string,uint256)": TypedContractEvent<
      EmergencyStopTriggeredEvent.InputTuple,
      EmergencyStopTriggeredEvent.OutputTuple,
      EmergencyStopTriggeredEvent.OutputObject
    >;
    EmergencyStopTriggered: TypedContractEvent<
      EmergencyStopTriggeredEvent.InputTuple,
      EmergencyStopTriggeredEvent.OutputTuple,
      EmergencyStopTriggeredEvent.OutputObject
    >;

    "OwnershipTransferred(address,address)": TypedContractEvent<
      OwnershipTransferredEvent.InputTuple,
      OwnershipTransferredEvent.OutputTuple,
      OwnershipTransferredEvent.OutputObject
    >;
    OwnershipTransferred: TypedContractEvent<
      OwnershipTransferredEvent.InputTuple,
      OwnershipTransferredEvent.OutputTuple,
      OwnershipTransferredEvent.OutputObject
    >;
  };
}
