/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "../common";

export type BetStruct = {
  player: AddressLike;
  gameType: BigNumberish;
  amount: BigNumberish;
  prediction: BigNumberish;
  result: BigNumberish;
  outcome: BigNumberish;
  payout: BigNumberish;
  timestamp: BigNumberish;
  blockNumber: BigNumberish;
};

export type BetStructOutput = [
  player: string,
  gameType: bigint,
  amount: bigint,
  prediction: bigint,
  result: bigint,
  outcome: bigint,
  payout: bigint,
  timestamp: bigint,
  blockNumber: bigint
] & {
  player: string;
  gameType: bigint;
  amount: bigint;
  prediction: bigint;
  result: bigint;
  outcome: bigint;
  payout: bigint;
  timestamp: bigint;
  blockNumber: bigint;
};

export interface CasinoInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "COIN_FLIP_MAX_BET"
      | "COOLDOWN_SECONDS"
      | "DICE_MAX_BET"
      | "HIGH_LOW_MAX_BET"
      | "HOUSE_EDGE_BPS"
      | "MAX_BET"
      | "MIN_BET"
      | "ROULETTE_MAX_BET"
      | "allBets"
      | "depositHouseFunds"
      | "emergencyWithdraw"
      | "getBetLimits"
      | "getHouseBalance"
      | "getHouseStats"
      | "getPlayerBets"
      | "getPlayerStats"
      | "houseTotalPaidOut"
      | "houseTotalProfit"
      | "houseTotalWagered"
      | "houseWallet"
      | "lastBetTimestamp"
      | "owner"
      | "pause"
      | "paused"
      | "placeBet"
      | "playerBets"
      | "renounceOwnership"
      | "totalLost"
      | "totalWagered"
      | "totalWon"
      | "transferOwnership"
      | "unpause"
      | "updateHouseWallet"
      | "usdt"
      | "withdrawHouseFunds"
  ): FunctionFragment;

  getEvent(
    nameOrSignatureOrTopic:
      | "BetPlaced"
      | "BetResult"
      | "HouseBalanceUpdated"
      | "OwnershipTransferred"
      | "Paused"
      | "Unpaused"
  ): EventFragment;

  encodeFunctionData(
    functionFragment: "COIN_FLIP_MAX_BET",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "COOLDOWN_SECONDS",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "DICE_MAX_BET",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "HIGH_LOW_MAX_BET",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "HOUSE_EDGE_BPS",
    values?: undefined
  ): string;
  encodeFunctionData(functionFragment: "MAX_BET", values?: undefined): string;
  encodeFunctionData(functionFragment: "MIN_BET", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "ROULETTE_MAX_BET",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "allBets",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "depositHouseFunds",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "emergencyWithdraw",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "getBetLimits",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getHouseBalance",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "getHouseStats",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "getPlayerBets",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "getPlayerStats",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "houseTotalPaidOut",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "houseTotalProfit",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "houseTotalWagered",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "houseWallet",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "lastBetTimestamp",
    values: [AddressLike]
  ): string;
  encodeFunctionData(functionFragment: "owner", values?: undefined): string;
  encodeFunctionData(functionFragment: "pause", values?: undefined): string;
  encodeFunctionData(functionFragment: "paused", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "placeBet",
    values: [BigNumberish, BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "playerBets",
    values: [AddressLike, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "renounceOwnership",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "totalLost",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "totalWagered",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "totalWon",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "transferOwnership",
    values: [AddressLike]
  ): string;
  encodeFunctionData(functionFragment: "unpause", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "updateHouseWallet",
    values: [AddressLike]
  ): string;
  encodeFunctionData(functionFragment: "usdt", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "withdrawHouseFunds",
    values: [BigNumberish]
  ): string;

  decodeFunctionResult(
    functionFragment: "COIN_FLIP_MAX_BET",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "COOLDOWN_SECONDS",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "DICE_MAX_BET",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "HIGH_LOW_MAX_BET",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "HOUSE_EDGE_BPS",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "MAX_BET", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "MIN_BET", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "ROULETTE_MAX_BET",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "allBets", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "depositHouseFunds",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "emergencyWithdraw",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getBetLimits",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getHouseBalance",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getHouseStats",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getPlayerBets",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getPlayerStats",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "houseTotalPaidOut",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "houseTotalProfit",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "houseTotalWagered",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "houseWallet",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "lastBetTimestamp",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "owner", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "pause", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "paused", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "placeBet", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "playerBets", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "renounceOwnership",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "totalLost", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "totalWagered",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "totalWon", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "transferOwnership",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "unpause", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "updateHouseWallet",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "usdt", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "withdrawHouseFunds",
    data: BytesLike
  ): Result;
}

export namespace BetPlacedEvent {
  export type InputTuple = [
    player: AddressLike,
    gameType: BigNumberish,
    amount: BigNumberish,
    prediction: BigNumberish,
    betId: BigNumberish
  ];
  export type OutputTuple = [
    player: string,
    gameType: bigint,
    amount: bigint,
    prediction: bigint,
    betId: bigint
  ];
  export interface OutputObject {
    player: string;
    gameType: bigint;
    amount: bigint;
    prediction: bigint;
    betId: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace BetResultEvent {
  export type InputTuple = [
    player: AddressLike,
    betId: BigNumberish,
    gameType: BigNumberish,
    prediction: BigNumberish,
    result: BigNumberish,
    outcome: BigNumberish,
    payout: BigNumberish
  ];
  export type OutputTuple = [
    player: string,
    betId: bigint,
    gameType: bigint,
    prediction: bigint,
    result: bigint,
    outcome: bigint,
    payout: bigint
  ];
  export interface OutputObject {
    player: string;
    betId: bigint;
    gameType: bigint;
    prediction: bigint;
    result: bigint;
    outcome: bigint;
    payout: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace HouseBalanceUpdatedEvent {
  export type InputTuple = [newBalance: BigNumberish, change: BigNumberish];
  export type OutputTuple = [newBalance: bigint, change: bigint];
  export interface OutputObject {
    newBalance: bigint;
    change: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace OwnershipTransferredEvent {
  export type InputTuple = [previousOwner: AddressLike, newOwner: AddressLike];
  export type OutputTuple = [previousOwner: string, newOwner: string];
  export interface OutputObject {
    previousOwner: string;
    newOwner: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace PausedEvent {
  export type InputTuple = [account: AddressLike];
  export type OutputTuple = [account: string];
  export interface OutputObject {
    account: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace UnpausedEvent {
  export type InputTuple = [account: AddressLike];
  export type OutputTuple = [account: string];
  export interface OutputObject {
    account: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface Casino extends BaseContract {
  connect(runner?: ContractRunner | null): Casino;
  waitForDeployment(): Promise<this>;

  interface: CasinoInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  COIN_FLIP_MAX_BET: TypedContractMethod<[], [bigint], "view">;

  COOLDOWN_SECONDS: TypedContractMethod<[], [bigint], "view">;

  DICE_MAX_BET: TypedContractMethod<[], [bigint], "view">;

  HIGH_LOW_MAX_BET: TypedContractMethod<[], [bigint], "view">;

  HOUSE_EDGE_BPS: TypedContractMethod<[], [bigint], "view">;

  MAX_BET: TypedContractMethod<[], [bigint], "view">;

  MIN_BET: TypedContractMethod<[], [bigint], "view">;

  ROULETTE_MAX_BET: TypedContractMethod<[], [bigint], "view">;

  allBets: TypedContractMethod<
    [arg0: BigNumberish],
    [
      [
        string,
        bigint,
        bigint,
        bigint,
        bigint,
        bigint,
        bigint,
        bigint,
        bigint
      ] & {
        player: string;
        gameType: bigint;
        amount: bigint;
        prediction: bigint;
        result: bigint;
        outcome: bigint;
        payout: bigint;
        timestamp: bigint;
        blockNumber: bigint;
      }
    ],
    "view"
  >;

  depositHouseFunds: TypedContractMethod<
    [_amount: BigNumberish],
    [void],
    "nonpayable"
  >;

  emergencyWithdraw: TypedContractMethod<[], [void], "nonpayable">;

  getBetLimits: TypedContractMethod<
    [_gameType: BigNumberish],
    [[bigint, bigint] & { min: bigint; max: bigint }],
    "view"
  >;

  getHouseBalance: TypedContractMethod<[], [bigint], "view">;

  getHouseStats: TypedContractMethod<
    [],
    [
      [bigint, bigint, bigint, bigint] & {
        totalWagered_: bigint;
        totalPaidOut: bigint;
        totalProfit: bigint;
        houseBalance: bigint;
      }
    ],
    "view"
  >;

  getPlayerBets: TypedContractMethod<
    [_player: AddressLike],
    [BetStructOutput[]],
    "view"
  >;

  getPlayerStats: TypedContractMethod<
    [_player: AddressLike],
    [
      [bigint, bigint, bigint, bigint] & {
        wagered: bigint;
        won: bigint;
        lost: bigint;
        netProfit: bigint;
      }
    ],
    "view"
  >;

  houseTotalPaidOut: TypedContractMethod<[], [bigint], "view">;

  houseTotalProfit: TypedContractMethod<[], [bigint], "view">;

  houseTotalWagered: TypedContractMethod<[], [bigint], "view">;

  houseWallet: TypedContractMethod<[], [string], "view">;

  lastBetTimestamp: TypedContractMethod<[arg0: AddressLike], [bigint], "view">;

  owner: TypedContractMethod<[], [string], "view">;

  pause: TypedContractMethod<[], [void], "nonpayable">;

  paused: TypedContractMethod<[], [boolean], "view">;

  placeBet: TypedContractMethod<
    [_gameType: BigNumberish, _amount: BigNumberish, _prediction: BigNumberish],
    [bigint],
    "nonpayable"
  >;

  playerBets: TypedContractMethod<
    [arg0: AddressLike, arg1: BigNumberish],
    [
      [
        string,
        bigint,
        bigint,
        bigint,
        bigint,
        bigint,
        bigint,
        bigint,
        bigint
      ] & {
        player: string;
        gameType: bigint;
        amount: bigint;
        prediction: bigint;
        result: bigint;
        outcome: bigint;
        payout: bigint;
        timestamp: bigint;
        blockNumber: bigint;
      }
    ],
    "view"
  >;

  renounceOwnership: TypedContractMethod<[], [void], "nonpayable">;

  totalLost: TypedContractMethod<[arg0: AddressLike], [bigint], "view">;

  totalWagered: TypedContractMethod<[arg0: AddressLike], [bigint], "view">;

  totalWon: TypedContractMethod<[arg0: AddressLike], [bigint], "view">;

  transferOwnership: TypedContractMethod<
    [newOwner: AddressLike],
    [void],
    "nonpayable"
  >;

  unpause: TypedContractMethod<[], [void], "nonpayable">;

  updateHouseWallet: TypedContractMethod<
    [_newHouseWallet: AddressLike],
    [void],
    "nonpayable"
  >;

  usdt: TypedContractMethod<[], [string], "view">;

  withdrawHouseFunds: TypedContractMethod<
    [_amount: BigNumberish],
    [void],
    "nonpayable"
  >;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "COIN_FLIP_MAX_BET"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "COOLDOWN_SECONDS"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "DICE_MAX_BET"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "HIGH_LOW_MAX_BET"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "HOUSE_EDGE_BPS"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "MAX_BET"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "MIN_BET"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "ROULETTE_MAX_BET"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "allBets"
  ): TypedContractMethod<
    [arg0: BigNumberish],
    [
      [
        string,
        bigint,
        bigint,
        bigint,
        bigint,
        bigint,
        bigint,
        bigint,
        bigint
      ] & {
        player: string;
        gameType: bigint;
        amount: bigint;
        prediction: bigint;
        result: bigint;
        outcome: bigint;
        payout: bigint;
        timestamp: bigint;
        blockNumber: bigint;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "depositHouseFunds"
  ): TypedContractMethod<[_amount: BigNumberish], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "emergencyWithdraw"
  ): TypedContractMethod<[], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "getBetLimits"
  ): TypedContractMethod<
    [_gameType: BigNumberish],
    [[bigint, bigint] & { min: bigint; max: bigint }],
    "view"
  >;
  getFunction(
    nameOrSignature: "getHouseBalance"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "getHouseStats"
  ): TypedContractMethod<
    [],
    [
      [bigint, bigint, bigint, bigint] & {
        totalWagered_: bigint;
        totalPaidOut: bigint;
        totalProfit: bigint;
        houseBalance: bigint;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "getPlayerBets"
  ): TypedContractMethod<[_player: AddressLike], [BetStructOutput[]], "view">;
  getFunction(
    nameOrSignature: "getPlayerStats"
  ): TypedContractMethod<
    [_player: AddressLike],
    [
      [bigint, bigint, bigint, bigint] & {
        wagered: bigint;
        won: bigint;
        lost: bigint;
        netProfit: bigint;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "houseTotalPaidOut"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "houseTotalProfit"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "houseTotalWagered"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "houseWallet"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "lastBetTimestamp"
  ): TypedContractMethod<[arg0: AddressLike], [bigint], "view">;
  getFunction(
    nameOrSignature: "owner"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "pause"
  ): TypedContractMethod<[], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "paused"
  ): TypedContractMethod<[], [boolean], "view">;
  getFunction(
    nameOrSignature: "placeBet"
  ): TypedContractMethod<
    [_gameType: BigNumberish, _amount: BigNumberish, _prediction: BigNumberish],
    [bigint],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "playerBets"
  ): TypedContractMethod<
    [arg0: AddressLike, arg1: BigNumberish],
    [
      [
        string,
        bigint,
        bigint,
        bigint,
        bigint,
        bigint,
        bigint,
        bigint,
        bigint
      ] & {
        player: string;
        gameType: bigint;
        amount: bigint;
        prediction: bigint;
        result: bigint;
        outcome: bigint;
        payout: bigint;
        timestamp: bigint;
        blockNumber: bigint;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "renounceOwnership"
  ): TypedContractMethod<[], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "totalLost"
  ): TypedContractMethod<[arg0: AddressLike], [bigint], "view">;
  getFunction(
    nameOrSignature: "totalWagered"
  ): TypedContractMethod<[arg0: AddressLike], [bigint], "view">;
  getFunction(
    nameOrSignature: "totalWon"
  ): TypedContractMethod<[arg0: AddressLike], [bigint], "view">;
  getFunction(
    nameOrSignature: "transferOwnership"
  ): TypedContractMethod<[newOwner: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "unpause"
  ): TypedContractMethod<[], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "updateHouseWallet"
  ): TypedContractMethod<[_newHouseWallet: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "usdt"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "withdrawHouseFunds"
  ): TypedContractMethod<[_amount: BigNumberish], [void], "nonpayable">;

  getEvent(
    key: "BetPlaced"
  ): TypedContractEvent<
    BetPlacedEvent.InputTuple,
    BetPlacedEvent.OutputTuple,
    BetPlacedEvent.OutputObject
  >;
  getEvent(
    key: "BetResult"
  ): TypedContractEvent<
    BetResultEvent.InputTuple,
    BetResultEvent.OutputTuple,
    BetResultEvent.OutputObject
  >;
  getEvent(
    key: "HouseBalanceUpdated"
  ): TypedContractEvent<
    HouseBalanceUpdatedEvent.InputTuple,
    HouseBalanceUpdatedEvent.OutputTuple,
    HouseBalanceUpdatedEvent.OutputObject
  >;
  getEvent(
    key: "OwnershipTransferred"
  ): TypedContractEvent<
    OwnershipTransferredEvent.InputTuple,
    OwnershipTransferredEvent.OutputTuple,
    OwnershipTransferredEvent.OutputObject
  >;
  getEvent(
    key: "Paused"
  ): TypedContractEvent<
    PausedEvent.InputTuple,
    PausedEvent.OutputTuple,
    PausedEvent.OutputObject
  >;
  getEvent(
    key: "Unpaused"
  ): TypedContractEvent<
    UnpausedEvent.InputTuple,
    UnpausedEvent.OutputTuple,
    UnpausedEvent.OutputObject
  >;

  filters: {
    "BetPlaced(address,uint8,uint256,uint256,uint256)": TypedContractEvent<
      BetPlacedEvent.InputTuple,
      BetPlacedEvent.OutputTuple,
      BetPlacedEvent.OutputObject
    >;
    BetPlaced: TypedContractEvent<
      BetPlacedEvent.InputTuple,
      BetPlacedEvent.OutputTuple,
      BetPlacedEvent.OutputObject
    >;

    "BetResult(address,uint256,uint8,uint256,uint256,uint8,uint256)": TypedContractEvent<
      BetResultEvent.InputTuple,
      BetResultEvent.OutputTuple,
      BetResultEvent.OutputObject
    >;
    BetResult: TypedContractEvent<
      BetResultEvent.InputTuple,
      BetResultEvent.OutputTuple,
      BetResultEvent.OutputObject
    >;

    "HouseBalanceUpdated(uint256,int256)": TypedContractEvent<
      HouseBalanceUpdatedEvent.InputTuple,
      HouseBalanceUpdatedEvent.OutputTuple,
      HouseBalanceUpdatedEvent.OutputObject
    >;
    HouseBalanceUpdated: TypedContractEvent<
      HouseBalanceUpdatedEvent.InputTuple,
      HouseBalanceUpdatedEvent.OutputTuple,
      HouseBalanceUpdatedEvent.OutputObject
    >;

    "OwnershipTransferred(address,address)": TypedContractEvent<
      OwnershipTransferredEvent.InputTuple,
      OwnershipTransferredEvent.OutputTuple,
      OwnershipTransferredEvent.OutputObject
    >;
    OwnershipTransferred: TypedContractEvent<
      OwnershipTransferredEvent.InputTuple,
      OwnershipTransferredEvent.OutputTuple,
      OwnershipTransferredEvent.OutputObject
    >;

    "Paused(address)": TypedContractEvent<
      PausedEvent.InputTuple,
      PausedEvent.OutputTuple,
      PausedEvent.OutputObject
    >;
    Paused: TypedContractEvent<
      PausedEvent.InputTuple,
      PausedEvent.OutputTuple,
      PausedEvent.OutputObject
    >;

    "Unpaused(address)": TypedContractEvent<
      UnpausedEvent.InputTuple,
      UnpausedEvent.OutputTuple,
      UnpausedEvent.OutputObject
    >;
    Unpaused: TypedContractEvent<
      UnpausedEvent.InputTuple,
      UnpausedEvent.OutputTuple,
      UnpausedEvent.OutputObject
    >;
  };
}
