/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "../common";

export type BetStruct = {
  wallet: AddressLike;
  marketId: string;
  choice: BigNumberish;
  amount: BigNumberish;
  timestamp: BigNumberish;
  betNumber: BigNumberish;
};

export type BetStructOutput = [
  wallet: string,
  marketId: string,
  choice: bigint,
  amount: bigint,
  timestamp: bigint,
  betNumber: bigint
] & {
  wallet: string;
  marketId: string;
  choice: bigint;
  amount: bigint;
  timestamp: bigint;
  betNumber: bigint;
};

export interface PredictionMarketInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "COOLDOWN_SECONDS"
      | "HOUSE_FEE_PERCENT"
      | "MAX_BET"
      | "MAX_BETS_IN_1_HOUR"
      | "MAX_BETS_PER_WALLET"
      | "MIN_BET"
      | "POOL_CAP_PERCENT"
      | "allBets"
      | "betCountPerWallet"
      | "closeMarket"
      | "createMarket"
      | "flagWallet"
      | "flaggedWallets"
      | "getBet"
      | "getBetCount"
      | "getCooldownRemaining"
      | "getMarket"
      | "getMarketTimeline"
      | "getPoolInfo"
      | "getUserBetCount"
      | "getUserBets"
      | "getWalletTotalBets"
      | "gnosisSafe"
      | "hasMarket"
      | "isPaused"
      | "isWalletFlagged"
      | "lastBetTimestamp"
      | "market"
      | "marketExists"
      | "owner"
      | "pauseContract"
      | "paused"
      | "placeBet"
      | "renounceOwnership"
      | "resetMarket"
      | "resolveMarket"
      | "transferOwnership"
      | "unflagWallet"
      | "unpauseContract"
      | "updateGnosisSafe"
      | "usdt"
      | "userBets"
      | "walletBetTimestamps"
  ): FunctionFragment;

  getEvent(
    nameOrSignatureOrTopic:
      | "BetPlaced"
      | "ContractPaused"
      | "ContractUnpaused"
      | "MarketClosed"
      | "MarketCreated"
      | "MarketResolved"
      | "OwnershipTransferred"
      | "Paused"
      | "PoolUpdated"
      | "Unpaused"
      | "WalletFlagged"
  ): EventFragment;

  encodeFunctionData(
    functionFragment: "COOLDOWN_SECONDS",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "HOUSE_FEE_PERCENT",
    values?: undefined
  ): string;
  encodeFunctionData(functionFragment: "MAX_BET", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "MAX_BETS_IN_1_HOUR",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "MAX_BETS_PER_WALLET",
    values?: undefined
  ): string;
  encodeFunctionData(functionFragment: "MIN_BET", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "POOL_CAP_PERCENT",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "allBets",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "betCountPerWallet",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "closeMarket",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "createMarket",
    values: [string, string, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "flagWallet",
    values: [AddressLike, string]
  ): string;
  encodeFunctionData(
    functionFragment: "flaggedWallets",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "getBet",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getBetCount",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "getCooldownRemaining",
    values: [AddressLike]
  ): string;
  encodeFunctionData(functionFragment: "getMarket", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "getMarketTimeline",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "getPoolInfo",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "getUserBetCount",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "getUserBets",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "getWalletTotalBets",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "gnosisSafe",
    values?: undefined
  ): string;
  encodeFunctionData(functionFragment: "hasMarket", values?: undefined): string;
  encodeFunctionData(functionFragment: "isPaused", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "isWalletFlagged",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "lastBetTimestamp",
    values: [AddressLike]
  ): string;
  encodeFunctionData(functionFragment: "market", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "marketExists",
    values?: undefined
  ): string;
  encodeFunctionData(functionFragment: "owner", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "pauseContract",
    values: [string]
  ): string;
  encodeFunctionData(functionFragment: "paused", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "placeBet",
    values: [BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "renounceOwnership",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "resetMarket",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "resolveMarket",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "transferOwnership",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "unflagWallet",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "unpauseContract",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "updateGnosisSafe",
    values: [AddressLike]
  ): string;
  encodeFunctionData(functionFragment: "usdt", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "userBets",
    values: [AddressLike, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "walletBetTimestamps",
    values: [AddressLike, BigNumberish]
  ): string;

  decodeFunctionResult(
    functionFragment: "COOLDOWN_SECONDS",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "HOUSE_FEE_PERCENT",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "MAX_BET", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "MAX_BETS_IN_1_HOUR",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "MAX_BETS_PER_WALLET",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "MIN_BET", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "POOL_CAP_PERCENT",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "allBets", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "betCountPerWallet",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "closeMarket",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "createMarket",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "flagWallet", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "flaggedWallets",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "getBet", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "getBetCount",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getCooldownRemaining",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "getMarket", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "getMarketTimeline",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getPoolInfo",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getUserBetCount",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getUserBets",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getWalletTotalBets",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "gnosisSafe", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "hasMarket", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "isPaused", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "isWalletFlagged",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "lastBetTimestamp",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "market", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "marketExists",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "owner", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "pauseContract",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "paused", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "placeBet", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "renounceOwnership",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "resetMarket",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "resolveMarket",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "transferOwnership",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "unflagWallet",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "unpauseContract",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "updateGnosisSafe",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "usdt", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "userBets", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "walletBetTimestamps",
    data: BytesLike
  ): Result;
}

export namespace BetPlacedEvent {
  export type InputTuple = [
    wallet: AddressLike,
    marketId: string,
    choice: BigNumberish,
    amount: BigNumberish,
    betNumber: BigNumberish,
    timestamp: BigNumberish
  ];
  export type OutputTuple = [
    wallet: string,
    marketId: string,
    choice: bigint,
    amount: bigint,
    betNumber: bigint,
    timestamp: bigint
  ];
  export interface OutputObject {
    wallet: string;
    marketId: string;
    choice: bigint;
    amount: bigint;
    betNumber: bigint;
    timestamp: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace ContractPausedEvent {
  export type InputTuple = [reason: string, timestamp: BigNumberish];
  export type OutputTuple = [reason: string, timestamp: bigint];
  export interface OutputObject {
    reason: string;
    timestamp: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace ContractUnpausedEvent {
  export type InputTuple = [timestamp: BigNumberish];
  export type OutputTuple = [timestamp: bigint];
  export interface OutputObject {
    timestamp: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace MarketClosedEvent {
  export type InputTuple = [marketId: string, timestamp: BigNumberish];
  export type OutputTuple = [marketId: string, timestamp: bigint];
  export interface OutputObject {
    marketId: string;
    timestamp: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace MarketCreatedEvent {
  export type InputTuple = [
    marketId: string,
    question: string,
    startTime: BigNumberish,
    endTime: BigNumberish
  ];
  export type OutputTuple = [
    marketId: string,
    question: string,
    startTime: bigint,
    endTime: bigint
  ];
  export interface OutputObject {
    marketId: string;
    question: string;
    startTime: bigint;
    endTime: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace MarketResolvedEvent {
  export type InputTuple = [
    marketId: string,
    winner: BigNumberish,
    timestamp: BigNumberish
  ];
  export type OutputTuple = [
    marketId: string,
    winner: bigint,
    timestamp: bigint
  ];
  export interface OutputObject {
    marketId: string;
    winner: bigint;
    timestamp: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace OwnershipTransferredEvent {
  export type InputTuple = [previousOwner: AddressLike, newOwner: AddressLike];
  export type OutputTuple = [previousOwner: string, newOwner: string];
  export interface OutputObject {
    previousOwner: string;
    newOwner: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace PausedEvent {
  export type InputTuple = [account: AddressLike];
  export type OutputTuple = [account: string];
  export interface OutputObject {
    account: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace PoolUpdatedEvent {
  export type InputTuple = [
    marketId: string,
    yesPool: BigNumberish,
    noPool: BigNumberish,
    timestamp: BigNumberish
  ];
  export type OutputTuple = [
    marketId: string,
    yesPool: bigint,
    noPool: bigint,
    timestamp: bigint
  ];
  export interface OutputObject {
    marketId: string;
    yesPool: bigint;
    noPool: bigint;
    timestamp: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace UnpausedEvent {
  export type InputTuple = [account: AddressLike];
  export type OutputTuple = [account: string];
  export interface OutputObject {
    account: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace WalletFlaggedEvent {
  export type InputTuple = [
    wallet: AddressLike,
    reason: string,
    timestamp: BigNumberish
  ];
  export type OutputTuple = [wallet: string, reason: string, timestamp: bigint];
  export interface OutputObject {
    wallet: string;
    reason: string;
    timestamp: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface PredictionMarket extends BaseContract {
  connect(runner?: ContractRunner | null): PredictionMarket;
  waitForDeployment(): Promise<this>;

  interface: PredictionMarketInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  COOLDOWN_SECONDS: TypedContractMethod<[], [bigint], "view">;

  HOUSE_FEE_PERCENT: TypedContractMethod<[], [bigint], "view">;

  MAX_BET: TypedContractMethod<[], [bigint], "view">;

  MAX_BETS_IN_1_HOUR: TypedContractMethod<[], [bigint], "view">;

  MAX_BETS_PER_WALLET: TypedContractMethod<[], [bigint], "view">;

  MIN_BET: TypedContractMethod<[], [bigint], "view">;

  POOL_CAP_PERCENT: TypedContractMethod<[], [bigint], "view">;

  allBets: TypedContractMethod<
    [arg0: BigNumberish],
    [
      [string, string, bigint, bigint, bigint, bigint] & {
        wallet: string;
        marketId: string;
        choice: bigint;
        amount: bigint;
        timestamp: bigint;
        betNumber: bigint;
      }
    ],
    "view"
  >;

  betCountPerWallet: TypedContractMethod<[arg0: AddressLike], [bigint], "view">;

  closeMarket: TypedContractMethod<[], [void], "nonpayable">;

  createMarket: TypedContractMethod<
    [_marketId: string, _question: string, _endTime: BigNumberish],
    [void],
    "nonpayable"
  >;

  flagWallet: TypedContractMethod<
    [_wallet: AddressLike, _reason: string],
    [void],
    "nonpayable"
  >;

  flaggedWallets: TypedContractMethod<[arg0: AddressLike], [boolean], "view">;

  getBet: TypedContractMethod<
    [_index: BigNumberish],
    [
      [string, string, bigint, bigint, bigint, bigint] & {
        wallet: string;
        marketId: string;
        choice: bigint;
        amount: bigint;
        timestamp: bigint;
        betNumber: bigint;
      }
    ],
    "view"
  >;

  getBetCount: TypedContractMethod<[], [bigint], "view">;

  getCooldownRemaining: TypedContractMethod<
    [_wallet: AddressLike],
    [bigint],
    "view"
  >;

  getMarket: TypedContractMethod<
    [],
    [
      [string, string, bigint, bigint, bigint, bigint, bigint, bigint] & {
        id: string;
        question: string;
        yesPool: bigint;
        noPool: bigint;
        startTime: bigint;
        endTime: bigint;
        status: bigint;
        winner: bigint;
      }
    ],
    "view"
  >;

  getMarketTimeline: TypedContractMethod<
    [],
    [
      [bigint, bigint, bigint, boolean] & {
        startTime: bigint;
        endTime: bigint;
        timeRemaining: bigint;
        hasEnded: boolean;
      }
    ],
    "view"
  >;

  getPoolInfo: TypedContractMethod<
    [],
    [
      [bigint, bigint, bigint, bigint, bigint] & {
        yesPool: bigint;
        noPool: bigint;
        totalPool: bigint;
        yesPercent: bigint;
        noPercent: bigint;
      }
    ],
    "view"
  >;

  getUserBetCount: TypedContractMethod<
    [_wallet: AddressLike],
    [bigint],
    "view"
  >;

  getUserBets: TypedContractMethod<
    [_wallet: AddressLike],
    [BetStructOutput[]],
    "view"
  >;

  getWalletTotalBets: TypedContractMethod<
    [_wallet: AddressLike],
    [bigint],
    "view"
  >;

  gnosisSafe: TypedContractMethod<[], [string], "view">;

  hasMarket: TypedContractMethod<[], [boolean], "view">;

  isPaused: TypedContractMethod<[], [boolean], "view">;

  isWalletFlagged: TypedContractMethod<
    [_wallet: AddressLike],
    [boolean],
    "view"
  >;

  lastBetTimestamp: TypedContractMethod<[arg0: AddressLike], [bigint], "view">;

  market: TypedContractMethod<
    [],
    [
      [string, string, bigint, bigint, bigint, bigint, bigint, bigint] & {
        id: string;
        question: string;
        yesPool: bigint;
        noPool: bigint;
        startTime: bigint;
        endTime: bigint;
        status: bigint;
        winner: bigint;
      }
    ],
    "view"
  >;

  marketExists: TypedContractMethod<[], [boolean], "view">;

  owner: TypedContractMethod<[], [string], "view">;

  pauseContract: TypedContractMethod<[_reason: string], [void], "nonpayable">;

  paused: TypedContractMethod<[], [boolean], "view">;

  placeBet: TypedContractMethod<
    [_choice: BigNumberish, _amount: BigNumberish],
    [void],
    "nonpayable"
  >;

  renounceOwnership: TypedContractMethod<[], [void], "nonpayable">;

  resetMarket: TypedContractMethod<[], [void], "nonpayable">;

  resolveMarket: TypedContractMethod<
    [_winner: BigNumberish],
    [void],
    "nonpayable"
  >;

  transferOwnership: TypedContractMethod<
    [newOwner: AddressLike],
    [void],
    "nonpayable"
  >;

  unflagWallet: TypedContractMethod<
    [_wallet: AddressLike],
    [void],
    "nonpayable"
  >;

  unpauseContract: TypedContractMethod<[], [void], "nonpayable">;

  updateGnosisSafe: TypedContractMethod<
    [_newGnosisSafe: AddressLike],
    [void],
    "nonpayable"
  >;

  usdt: TypedContractMethod<[], [string], "view">;

  userBets: TypedContractMethod<
    [arg0: AddressLike, arg1: BigNumberish],
    [
      [string, string, bigint, bigint, bigint, bigint] & {
        wallet: string;
        marketId: string;
        choice: bigint;
        amount: bigint;
        timestamp: bigint;
        betNumber: bigint;
      }
    ],
    "view"
  >;

  walletBetTimestamps: TypedContractMethod<
    [arg0: AddressLike, arg1: BigNumberish],
    [bigint],
    "view"
  >;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "COOLDOWN_SECONDS"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "HOUSE_FEE_PERCENT"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "MAX_BET"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "MAX_BETS_IN_1_HOUR"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "MAX_BETS_PER_WALLET"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "MIN_BET"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "POOL_CAP_PERCENT"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "allBets"
  ): TypedContractMethod<
    [arg0: BigNumberish],
    [
      [string, string, bigint, bigint, bigint, bigint] & {
        wallet: string;
        marketId: string;
        choice: bigint;
        amount: bigint;
        timestamp: bigint;
        betNumber: bigint;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "betCountPerWallet"
  ): TypedContractMethod<[arg0: AddressLike], [bigint], "view">;
  getFunction(
    nameOrSignature: "closeMarket"
  ): TypedContractMethod<[], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "createMarket"
  ): TypedContractMethod<
    [_marketId: string, _question: string, _endTime: BigNumberish],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "flagWallet"
  ): TypedContractMethod<
    [_wallet: AddressLike, _reason: string],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "flaggedWallets"
  ): TypedContractMethod<[arg0: AddressLike], [boolean], "view">;
  getFunction(
    nameOrSignature: "getBet"
  ): TypedContractMethod<
    [_index: BigNumberish],
    [
      [string, string, bigint, bigint, bigint, bigint] & {
        wallet: string;
        marketId: string;
        choice: bigint;
        amount: bigint;
        timestamp: bigint;
        betNumber: bigint;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "getBetCount"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "getCooldownRemaining"
  ): TypedContractMethod<[_wallet: AddressLike], [bigint], "view">;
  getFunction(
    nameOrSignature: "getMarket"
  ): TypedContractMethod<
    [],
    [
      [string, string, bigint, bigint, bigint, bigint, bigint, bigint] & {
        id: string;
        question: string;
        yesPool: bigint;
        noPool: bigint;
        startTime: bigint;
        endTime: bigint;
        status: bigint;
        winner: bigint;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "getMarketTimeline"
  ): TypedContractMethod<
    [],
    [
      [bigint, bigint, bigint, boolean] & {
        startTime: bigint;
        endTime: bigint;
        timeRemaining: bigint;
        hasEnded: boolean;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "getPoolInfo"
  ): TypedContractMethod<
    [],
    [
      [bigint, bigint, bigint, bigint, bigint] & {
        yesPool: bigint;
        noPool: bigint;
        totalPool: bigint;
        yesPercent: bigint;
        noPercent: bigint;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "getUserBetCount"
  ): TypedContractMethod<[_wallet: AddressLike], [bigint], "view">;
  getFunction(
    nameOrSignature: "getUserBets"
  ): TypedContractMethod<[_wallet: AddressLike], [BetStructOutput[]], "view">;
  getFunction(
    nameOrSignature: "getWalletTotalBets"
  ): TypedContractMethod<[_wallet: AddressLike], [bigint], "view">;
  getFunction(
    nameOrSignature: "gnosisSafe"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "hasMarket"
  ): TypedContractMethod<[], [boolean], "view">;
  getFunction(
    nameOrSignature: "isPaused"
  ): TypedContractMethod<[], [boolean], "view">;
  getFunction(
    nameOrSignature: "isWalletFlagged"
  ): TypedContractMethod<[_wallet: AddressLike], [boolean], "view">;
  getFunction(
    nameOrSignature: "lastBetTimestamp"
  ): TypedContractMethod<[arg0: AddressLike], [bigint], "view">;
  getFunction(
    nameOrSignature: "market"
  ): TypedContractMethod<
    [],
    [
      [string, string, bigint, bigint, bigint, bigint, bigint, bigint] & {
        id: string;
        question: string;
        yesPool: bigint;
        noPool: bigint;
        startTime: bigint;
        endTime: bigint;
        status: bigint;
        winner: bigint;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "marketExists"
  ): TypedContractMethod<[], [boolean], "view">;
  getFunction(
    nameOrSignature: "owner"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "pauseContract"
  ): TypedContractMethod<[_reason: string], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "paused"
  ): TypedContractMethod<[], [boolean], "view">;
  getFunction(
    nameOrSignature: "placeBet"
  ): TypedContractMethod<
    [_choice: BigNumberish, _amount: BigNumberish],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "renounceOwnership"
  ): TypedContractMethod<[], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "resetMarket"
  ): TypedContractMethod<[], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "resolveMarket"
  ): TypedContractMethod<[_winner: BigNumberish], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "transferOwnership"
  ): TypedContractMethod<[newOwner: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "unflagWallet"
  ): TypedContractMethod<[_wallet: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "unpauseContract"
  ): TypedContractMethod<[], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "updateGnosisSafe"
  ): TypedContractMethod<[_newGnosisSafe: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "usdt"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "userBets"
  ): TypedContractMethod<
    [arg0: AddressLike, arg1: BigNumberish],
    [
      [string, string, bigint, bigint, bigint, bigint] & {
        wallet: string;
        marketId: string;
        choice: bigint;
        amount: bigint;
        timestamp: bigint;
        betNumber: bigint;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "walletBetTimestamps"
  ): TypedContractMethod<
    [arg0: AddressLike, arg1: BigNumberish],
    [bigint],
    "view"
  >;

  getEvent(
    key: "BetPlaced"
  ): TypedContractEvent<
    BetPlacedEvent.InputTuple,
    BetPlacedEvent.OutputTuple,
    BetPlacedEvent.OutputObject
  >;
  getEvent(
    key: "ContractPaused"
  ): TypedContractEvent<
    ContractPausedEvent.InputTuple,
    ContractPausedEvent.OutputTuple,
    ContractPausedEvent.OutputObject
  >;
  getEvent(
    key: "ContractUnpaused"
  ): TypedContractEvent<
    ContractUnpausedEvent.InputTuple,
    ContractUnpausedEvent.OutputTuple,
    ContractUnpausedEvent.OutputObject
  >;
  getEvent(
    key: "MarketClosed"
  ): TypedContractEvent<
    MarketClosedEvent.InputTuple,
    MarketClosedEvent.OutputTuple,
    MarketClosedEvent.OutputObject
  >;
  getEvent(
    key: "MarketCreated"
  ): TypedContractEvent<
    MarketCreatedEvent.InputTuple,
    MarketCreatedEvent.OutputTuple,
    MarketCreatedEvent.OutputObject
  >;
  getEvent(
    key: "MarketResolved"
  ): TypedContractEvent<
    MarketResolvedEvent.InputTuple,
    MarketResolvedEvent.OutputTuple,
    MarketResolvedEvent.OutputObject
  >;
  getEvent(
    key: "OwnershipTransferred"
  ): TypedContractEvent<
    OwnershipTransferredEvent.InputTuple,
    OwnershipTransferredEvent.OutputTuple,
    OwnershipTransferredEvent.OutputObject
  >;
  getEvent(
    key: "Paused"
  ): TypedContractEvent<
    PausedEvent.InputTuple,
    PausedEvent.OutputTuple,
    PausedEvent.OutputObject
  >;
  getEvent(
    key: "PoolUpdated"
  ): TypedContractEvent<
    PoolUpdatedEvent.InputTuple,
    PoolUpdatedEvent.OutputTuple,
    PoolUpdatedEvent.OutputObject
  >;
  getEvent(
    key: "Unpaused"
  ): TypedContractEvent<
    UnpausedEvent.InputTuple,
    UnpausedEvent.OutputTuple,
    UnpausedEvent.OutputObject
  >;
  getEvent(
    key: "WalletFlagged"
  ): TypedContractEvent<
    WalletFlaggedEvent.InputTuple,
    WalletFlaggedEvent.OutputTuple,
    WalletFlaggedEvent.OutputObject
  >;

  filters: {
    "BetPlaced(address,string,uint8,uint256,uint256,uint256)": TypedContractEvent<
      BetPlacedEvent.InputTuple,
      BetPlacedEvent.OutputTuple,
      BetPlacedEvent.OutputObject
    >;
    BetPlaced: TypedContractEvent<
      BetPlacedEvent.InputTuple,
      BetPlacedEvent.OutputTuple,
      BetPlacedEvent.OutputObject
    >;

    "ContractPaused(string,uint256)": TypedContractEvent<
      ContractPausedEvent.InputTuple,
      ContractPausedEvent.OutputTuple,
      ContractPausedEvent.OutputObject
    >;
    ContractPaused: TypedContractEvent<
      ContractPausedEvent.InputTuple,
      ContractPausedEvent.OutputTuple,
      ContractPausedEvent.OutputObject
    >;

    "ContractUnpaused(uint256)": TypedContractEvent<
      ContractUnpausedEvent.InputTuple,
      ContractUnpausedEvent.OutputTuple,
      ContractUnpausedEvent.OutputObject
    >;
    ContractUnpaused: TypedContractEvent<
      ContractUnpausedEvent.InputTuple,
      ContractUnpausedEvent.OutputTuple,
      ContractUnpausedEvent.OutputObject
    >;

    "MarketClosed(string,uint256)": TypedContractEvent<
      MarketClosedEvent.InputTuple,
      MarketClosedEvent.OutputTuple,
      MarketClosedEvent.OutputObject
    >;
    MarketClosed: TypedContractEvent<
      MarketClosedEvent.InputTuple,
      MarketClosedEvent.OutputTuple,
      MarketClosedEvent.OutputObject
    >;

    "MarketCreated(string,string,uint256,uint256)": TypedContractEvent<
      MarketCreatedEvent.InputTuple,
      MarketCreatedEvent.OutputTuple,
      MarketCreatedEvent.OutputObject
    >;
    MarketCreated: TypedContractEvent<
      MarketCreatedEvent.InputTuple,
      MarketCreatedEvent.OutputTuple,
      MarketCreatedEvent.OutputObject
    >;

    "MarketResolved(string,uint8,uint256)": TypedContractEvent<
      MarketResolvedEvent.InputTuple,
      MarketResolvedEvent.OutputTuple,
      MarketResolvedEvent.OutputObject
    >;
    MarketResolved: TypedContractEvent<
      MarketResolvedEvent.InputTuple,
      MarketResolvedEvent.OutputTuple,
      MarketResolvedEvent.OutputObject
    >;

    "OwnershipTransferred(address,address)": TypedContractEvent<
      OwnershipTransferredEvent.InputTuple,
      OwnershipTransferredEvent.OutputTuple,
      OwnershipTransferredEvent.OutputObject
    >;
    OwnershipTransferred: TypedContractEvent<
      OwnershipTransferredEvent.InputTuple,
      OwnershipTransferredEvent.OutputTuple,
      OwnershipTransferredEvent.OutputObject
    >;

    "Paused(address)": TypedContractEvent<
      PausedEvent.InputTuple,
      PausedEvent.OutputTuple,
      PausedEvent.OutputObject
    >;
    Paused: TypedContractEvent<
      PausedEvent.InputTuple,
      PausedEvent.OutputTuple,
      PausedEvent.OutputObject
    >;

    "PoolUpdated(string,uint256,uint256,uint256)": TypedContractEvent<
      PoolUpdatedEvent.InputTuple,
      PoolUpdatedEvent.OutputTuple,
      PoolUpdatedEvent.OutputObject
    >;
    PoolUpdated: TypedContractEvent<
      PoolUpdatedEvent.InputTuple,
      PoolUpdatedEvent.OutputTuple,
      PoolUpdatedEvent.OutputObject
    >;

    "Unpaused(address)": TypedContractEvent<
      UnpausedEvent.InputTuple,
      UnpausedEvent.OutputTuple,
      UnpausedEvent.OutputObject
    >;
    Unpaused: TypedContractEvent<
      UnpausedEvent.InputTuple,
      UnpausedEvent.OutputTuple,
      UnpausedEvent.OutputObject
    >;

    "WalletFlagged(address,string,uint256)": TypedContractEvent<
      WalletFlaggedEvent.InputTuple,
      WalletFlaggedEvent.OutputTuple,
      WalletFlaggedEvent.OutputObject
    >;
    WalletFlagged: TypedContractEvent<
      WalletFlaggedEvent.InputTuple,
      WalletFlaggedEvent.OutputTuple,
      WalletFlaggedEvent.OutputObject
    >;
  };
}
